<option value="Sport">{{ __('data.Sport') }}</option>
<option value="Reading">{{ __('data.Reading') }}</option>
<option value="Writing">{{ __('data.Writing') }}</option>
<option value="Travel">{{ __('data.Travel') }}</option>
<option value="Games">{{ __('data.Games') }}</option>
<option value="Computer">{{ __('data.Computer') }}</option>
<option value="Spoking">{{ __('data.Spoking') }}</option>
<option value="Go to cafe">{{ __('data.Go to cafe') }}</option>
<option value="Rough games">{{ __('data.Rough games') }}</option>
<option value="Chess">{{ __('data.Chess') }}</option>
<option value="Disko">{{ __('data.Disko') }}</option>
<option value="Stay at natural">{{ __('data.Stay at natural') }}</option>
<option value="Action games">{{ __('data.Action games') }}</option>
<option value="Watching movies">{{ __('data.Watching movies') }}</option>
<option value="Watching cartoon movies">{{ __('data.Watching cartoon movies') }}</option>
<option value="going out With friends">{{ __('data.going out With friends') }}</option>
<option value="Walking">{{ __('data.Walking') }}</option>
