<option value="Normal">{{ __('data.Normal') }}</option>
<option value="Neural">{{ __('data.Neural') }}</option>
<option value="Romantic">{{ __('data.Romantic') }}</option>
<option value="Very sensitive">{{ __('data.Very sensitive') }}</option>
<option value="Irritable">{{ __('data.Irritable') }}</option>
<option value="quick to get angry">{{ __('data.quick to get angry') }}</option>
<option value="Calm">{{ __('data.Calm') }}</option>
<option value="Suspicious">{{ __('data.Suspicious') }}</option>
<option value="Curious">{{ __('data.Curious') }}</option>
<option value="Sly">{{ __('data.Sly') }}</option>
<option value="Cheerful">{{ __('data.Cheerful') }}</option>
