<option value="Feel">{{ __('data.Feel') }}</option>
<option value="Dismissal predecessor">{{ __('data.Dismissal predecessor') }}</option>
<option value="Sufi of the Sunnah">{{ __('data.Sufi of the Sunnah') }}</option>
<option value="Zedy Munkar">{{ __('data.Zedy Munkar') }}</option>
<option value="Jaafari">{{ __('data.Jaafari') }}</option>
<option value="Matrade">{{ __('data.Matrade') }}</option>
<option value="Abadi">{{ __('data.Abadi') }}</option>
<option value="My income">{{ __('data.My income') }}</option>
<option value="brothers">{{ __('data.brothers') }}</option>
<option value="Ethiopian">{{ __('data.Ethiopian') }}</option>
<option value="Protestant">{{ __('data.Protestant') }}</option>
<option value="Catholic">{{ __('data.Catholic') }}</option>
<option value="Autodox">{{ __('data.Autodox') }}</option>
<option value="I do not know">{{ __('data.I do not know') }}</option>
<option value="other">{{ __('data.other') }}</option>
