<option value="feel">{{ __('settings.feel') }}</option>
<option value="Dismissal predecessor">{{ __('settings.Dismissal predecessor') }}</option>
<option value="Sufi of the Sunnah">{{ __('settings.Sufi of the Sunnah') }}</option>
<option value="Zedy Munkar">{{ __('settings.Zedy Munkar') }}</option>
<option value="Jaafari">{{ __('settings.Jaafari') }}</option>
<option value="Matrade">{{ __('settings.Matrade') }}</option>
<option value="Abadi">{{ __('settings.Abadi') }}</option>
<option value="my income">{{ __('settings.my income') }}</option>
<option value="brothers">{{ __('settings.brothers') }}</option>
<option value="Ethiopian">{{ __('settings.Ethiopian') }}</option>
<option value="Protestant">{{ __('settings.Protestant') }}</option>
<option value="Catholic">{{ __('settings.Catholic') }}</option>
<option value="Autodox">{{ __('settings.Autodox') }}</option>
<option value="I do not know">{{ __('settings.I do not know') }}</option>
<option value="other">{{ __('settings.other') }}</option>
