<option value="1">{{ __('filter.less than that') }}</option>
<option value="2">{{ __('filter.from 50 to 60 kg') }}</option>
<option value="3">{{ __('filter.from 60 to 70 kg') }}</option>
<option value="4">{{ __('filter.from 70 to 80 kg') }}</option>
<option value="5">{{ __('filter.from 80 to 90 kg') }}</option>
<option value="6">{{ __('filter.from 90 to 100 kg') }}</option>
<option value="7">{{ __('filter.from 100 to 110 kg') }}</option>
<option value="8">{{ __('filter.from 110 to 120 kg') }}</option>
<option value="9">{{ __('filter.from 120 to 130 kg') }}</option>
<option value="10">{{ __('filter.from 130 to 140 kg') }}</option>
<option value="11">{{ __('filter.from 140 to 150 kg') }}</option>
<option value="12">{{ __('filter.from 150 to 160 kg') }}</option>
<option value="13">{{ __('filter.from 160 to 170 kg') }}</option>
<option value="14">{{ __('filter.from 170 to 180 kg') }}</option>
<option value="15">{{ __('filter.more than that') }}</option>
